---
node_js:
  - 16.1
rvm:
  - 3.0
cache:
  directories:
  - node_modules
  - vendor
before_script:
  - gem install bundler
  - npm install -g gulp yarn
script:
  - gulp build
install:
  - npm install
  - npm run build
